title: Dr. Ivan Fanin,
#logo:
description: I am did my  PhD in teh field of Political Sciences. And scince that I am a political analysis and obersving enthusiast
#show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
